spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vueblog?useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 831143
mybatis-plus:
  mapper-locations: classpath*:/com/meandi/mapper/xml/**Mapper.xml
server:
  port: 8081
